### PR TITLE
Add new fields to index

### PR DESCRIPTION
**Pull request by GeekArthur**
Signed-off-by: jingfu wang <jingfwan@redhat.com>

**Please specify the area for this PR**
Area: registry

**What does does this PR do / why we need it**:
This PR adds the following fields to index file:
- version
- icon
- attributes
- globalMemoryLimit

**Which issue(s) this PR fixes**:

Fixes https://github.com/devfile/api/issues/375

**PR acceptance criteria**:

- [x] Test (WIP) 

- [x] Documentation (WIP)

**How to test changes / Special notes to the reviewer**:
1. Build the index generator binary then create index.json then verify newly added fields are in index.json

### CODE REVIEW

**Comment by johnmcollier** [comment]
Are we publishing the index schema (and changes like these) to the devfile website yet?

**Review by johnmcollier — COMMENTED** [review]
Changes generally look good. Do we need to update the generator for these new fields too?

**Comment by GeekArthur** [comment]
> (Unrelated to these changes) Are we publishing the index schema (and changes like these) to the devfile website yet?

Yes, they are already in https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html under metadata fields.

**Comment by GeekArthur** [comment]
> Changes generally look good. Do we need to update the generator for these new fields too?

We don't need to do additional update for the generator, the generator will automatically parse the new fields according to the schema we update.

**Comment by johnmcollier** [comment]
> Yes, they are already in https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html under metadata field.

I mean the index.json schema, wasn't there a plan to publish the index schema on the devfile website?

**Comment by GeekArthur** [comment]
> > Yes, they are already in https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html under metadata field.
> 
> I mean the index.json schema, wasn't there a plan to publish the index schema on the devfile website?

Yeah, there is a plan https://github.com/devfile/api/issues/195 but it's completed yet, IIRC from last discussion docs team needs to put some design for it, so for the timing being we can only rely on the comments from index schema, there is no public host for the index schema on our website.

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
