### PR TITLE
Update to Go 1.19

### PR DESCRIPTION
**Pull request by michael-valdron**
**Please specify the area for this PR**

**What does does this PR do / why we need it**:

Updates registry support services to Go 1.19 with dependency updates.

**Which issue(s) this PR fixes**:

Fixes #?

fixes https://github.com/devfile/api/issues/1469

**PR acceptance criteria**:

- [x] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?

Documentation (WIP)
- [ ] Does the [REST API doc](../index/server/registry-REST-API.adoc) need to be updated with your changes?
- [ ] Does the [registry library doc](../registry-library/README.md) need to be updated with your changes?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by michael-valdron** [comment]
> Does the [REST API doc](https://github.com/devfile/registry-support/index/server/registry-REST-API.adoc) need to be updated with your changes?
> Does the [registry library doc](https://github.com/devfile/registry-support/registry-library/README.md) need to be updated with your changes?

Not needed for these changes.

**Review by thepetk — APPROVED** [review]
/lgtm I was able to build the registry image locally.

**Comment by michael-valdron** [comment]
/hold

In order to merge this without problems with our community registry deploy, I'll need to block updates to the `devfile-index-base` image under devfile/registry until https://github.com/devfile/api/issues/1473 is resolved.

**Comment by michael-valdron** [comment]
> /hold
> 
> In order to merge this without problems with our community registry deploy, I'll need to block updates to the `devfile-index-base` image under devfile/registry until [devfile/api#1473](https://github.com/devfile/api/issues/1473) is resolved.

Opened PR under devfile/registry to freeze the state of `devfile-index-base`: https://github.com/devfile/registry/pull/316

**Comment by michael-valdron** [comment]
/unhold

devfile/registry#316 has been merged and community registry reference to this repository is frozen until devfile/api#1473 is resolved.

**Pull request merged**
