### PR TITLE
fixed: index server shouldn't return null if no samples exist #540

### PR DESCRIPTION
**Pull request by Horiodino**
**Please specify the area for this PR**

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #https://github.com/devfile/api/issues/540

**PR acceptance criteria**:

- [ ] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?

Documentation (WIP)
- [ ] Does the [REST API doc](../index/server/registry-REST-API.adoc) need to be updated with your changes?
- [ ] Does the [registry library doc](../registry-library/README.md) need to be updated with your changes?

**How to test changes / Special notes to the reviewer**: uncertain for now!

### CODE REVIEW

**Comment by Horiodino** [comment]
i tried building the image , build sucessfully both the index-server-base and the devfile-index using`build_registry.sh`  but not getting how i can test it , need some help here

**Comment by michael-valdron** [comment]
@Horiodino Thanks for your contribution!

> build sucessfully both the index-server-base and the devfile-index using`build_registry.sh` but not getting how i can test it

You can test using both the **unit tests** and the **integration tests**. For the **unit test**, this can be done by running `cd index/server && go test ./...`, more information [here](https://github.com/devfile/registry-support/blob/main/index/server/README.md#testing).

For **integration tests**, you'll first need to deploy your built image to an environment like minikube then you can build and run the integration test suite against the deployed registry, here are some steps:

1. Use one of the [deployment methods](https://github.com/devfile/registry-support/tree/main#deploy) to deploy your image, I'd suggest the [helm chart](https://github.com/devfile/registry-support/tree/main?tab=readme-ov-file#via-the-devfile-registry-helm-chart), if you don't have helm installed you can do so by following the [user guide](https://helm.sh/docs/intro/install/), the following is an example of `helm` usage for this case:
```sh
helm install devfile-registry ./deploy/chart/devfile-registry \
  --set global.ingress.domain="$(minikube ip).nip.io" \
  --set devfileIndex.image=<your_image_name> \
  --set devfileIndex.tag=<your_image_tag>
```
2. Build the integration test suite image:
```sh
# Change your pwd to 'tests/integration' subdirectory
cd tests/integration

# Execute the build script
bash docker-build.sh
```
3. Run the integration test suite against your target registry using `docker`:
```sh
# Set your target registry to be your local deployments ingress address
export REGISTRY="http://devfile-registry-<deployment_namespace>.$(minikube ip).nip.io"

# Run test cases using docker
docker run --env REGISTRY=$REGISTRY --env IS_TEST_REGISTRY=true devfile-registry-integration
```

**Note**: You can also use your deployment directly to test your change out manually. Also when testing out your change, remember to remove `tests/registry/extraDevfileEntries.yaml` locally before building the registry to get one _without samples_ (perhaps just rename to `extraDevfileEntries.yaml.backup` and revert after building).

I will also be running these tests during my review.

> oh sorry for the signoff i will fix it

No problem, will also ask you to rebase your branch.

**Comment by Horiodino** [comment]
the unit test is sucessful but getting errors while building image  (integration test )

**Comment by Jdubrick** [comment]
FYI this is the issue he is having building the image: https://kubernetes.slack.com/archives/C02SX9E5B55/p1717674327962549

**Comment by Jdubrick** [comment]
> the unit test is sucessful but getting errors while building image (integration test )

@Horiodino Can you rebase? I want to see if the same error is replicated on our CI

**Comment by Horiodino** [comment]
> Fixes #[devfile/api#540](https://github.com/devfile/api/issues/540)

https://github.com/devfile/registry-support/pull/246

**Pull request closed without merging**
