### PR TITLE
Add and update license headers

### PR DESCRIPTION
**Pull request by michael-valdron**
**Please specify the area for this PR**

**What does does this PR do / why we need it**:

Adds and updates license headers in all source files, script files, and configuration files. License header changes were completed in devfile/api#1242.

_Additional changes_: Adds logging of diffs when generation of source is different than generated source changes in commits.

**Which issue(s) this PR fixes**:

Fixes #?

fixes devfile/api#1294

**PR acceptance criteria**:

- [x] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?

Documentation (WIP)
- [x] Does the [REST API doc](../index/server/registry-REST-API.adoc) need to be updated with your changes?
- [x] Does the [registry library doc](../registry-library/README.md) need to be updated with your changes?

**How to test changes / Special notes to the reviewer**:

For `oapi-codegen` use the following to install: `go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.12.4`

### CODE REVIEW

**Comment by michael-valdron** [comment]
> _Additional changes_: Adds logging of diffs when generation of source is different than generated source changes in commits.

fixed in https://github.com/devfile/registry-support/pull/186/commits/135d00eea7638c34f0d51f6449e53d79962eab0c

**Comment by michael-valdron** [comment]
Testing is blocked: https://github.com/devfile/api/issues/1294#issuecomment-1769510205

**Review by thepetk — CHANGES_REQUESTED** [review]
@michael-valdron I think we need to rebase to the latest main to fix the check which fails atm

**Comment by michael-valdron** [comment]
> @michael-valdron I think we need to rebase to the latest main to fix the check which fails atm

Yeah forgot to rebase the fix in, rebasing now..

**Review by thepetk — APPROVED** [review]

**Pull request merged**
