### PR TITLE
Feature: Index Schema Field Filtering

### PR DESCRIPTION
**Pull request by michael-valdron**
**Please specify the area for this PR**

**What does does this PR do / why we need it**:

Adds field-based filtering of index schemas with fuzzy search and *and* logical based filter stacking, e.g. filter by `name` **and** `description`.

Additional Changes:
- Added `deprecated` filter parameter and filter process: https://github.com/devfile/api/issues/959#issuecomment-2040398626
- Endpoint unit tests now use generated `ServerInterfaceWrapper` rather than explicitly defined `Server` that implements generated `ServerInterface` to better test parameter wrapper along with greatly increasing code coverage, see [endpoint_test.go#L481](https://github.com/michael-valdron/devfile-registry-support/blob/47a41977555c059702ab72319e228dba046948da/index/server/pkg/server/endpoint_test.go#L481) for an example of this change
- Use of `github.com/mohae/deepcopy` in filter to produce a different copy of the filtered index schema
- Use of `github.com/hashicorp/go-set` to use sets where it is more efficient
- Use of `k8s.io/apiextensions-apiserver` to set field pointers easier
- Introduction of new helper functions
  - `StructToMap` to transform a struct type into a `map[string]any`
  - `StrPtrIsSet` to return the result of `ptr != nil && *ptr != ""` for string pointers
- Introduction of `IndexParams` and `toIndexParams` receiver functions to generalize index endpoint parameter types from generated source
- Removal of GET method parameters from not allowed method handlers
- Correct typos under endpoint unit tests

**Which issue(s) this PR fixes**:

Fixes #?

fixes devfile/api#959

**PR acceptance criteria**:

- [x] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?

Documentation (WIP)
- [x] Does the [REST API doc](../index/server/registry-REST-API.adoc) need to be updated with your changes?
- [ ] Does the [registry library doc](../registry-library/README.md) need to be updated with your changes?

**How to test changes / Special notes to the reviewer**:
1. [Build devfile-index image from change](https://github.com/devfile/registry-support#build)
2. [Deploy built devfile-index image](https://github.com/devfile/registry-support#deploy)
3. [Build](https://github.com/devfile/registry-support/tree/main/tests/integration#build) & [run](https://github.com/devfile/registry-support/tree/main/tests/integration#run-in-a-container) altered integration test suite on deployment of built devfile-index from step 1
4. Run `cd index/server && go test ./...` to run unit tests on changes

### CODE REVIEW

**Review by thepetk — COMMENTED** [review]
@michael-valdron I've tried to build locally and test the new `devfile-index` image with minikube. When I'm trying to get filtered results I get the full list of stacks. What I'm trying to fetch is:

```
http://devfile-registry-default.<IP>.nip.io/v2index?name=python
```
Any ideas on what I'm doing wrong?

**Comment by michael-valdron** [comment]
> @michael-valdron I've tried to build locally and test the new devfile-index image with minikube. When I'm trying to get filtered results I get the full list of stacks. What I'm trying to fetch is:
>
> ```
> http://devfile-registry-default.<IP>.nip.io/v2index?name=python
> ```

@thepetk This is because this endpoint `/v2index` (and `/v2index/stack`) only queries stacks whereas the only python entry in the test registry is a sample, you can pull the desired result with:

```sh
curl http://devfile-registry-default.<IP>.nip.io/v2index/sample?name=python
```

You can filter this against stacks and samples with:

```sh
curl http://devfile-registry-default.<IP>.nip.io/v2index/all?name=python
```

**Comment by michael-valdron** [comment]
>> When I'm trying to get filtered results I get the full list of stacks.
>
> I wasn't able to reproduce exactly what you got (all stacks)

@thepetk What steps did you do to build and deploy? Maybe there is something else missed.

**Comment by thepetk** [comment]
> ```shell
> curl http://devfile-registry-default.<IP>.nip.io/v2index/sample?name=python
> ```

I'll re-do again all steps just to avoid the case that the devfile-index image wasn't up-to-date

**Review by thepetk — COMMENTED** [review]
@michael-valdron as we've checked together (thanks for the help debugging my issue!), I'd suggest adding a custom field for `deprecated` stacks.

This way when someone needs to fetch a deprecated stack (a stack with the `Deprecated` tag inside the default tags) will fetch only the fully deprecated stacks (without a supported version).

e.g

```
https://<host>/v2index/all?deprecated=true
```

**Comment by thepetk** [comment]
> @michael-valdron I've tried to build locally and test the new `devfile-index` image with minikube. When I'm trying to get filtered results I get the full list of stacks. What I'm trying to fetch is:
> 
> ```
> http://devfile-registry-default.<IP>.nip.io/v2index?name=python
> ```
> 
> Any ideas on what I'm doing wrong?
> 
> The dockerfile I'm using to build the image is:
> 
> ```dockerfile
> FROM registry.access.redhat.com/ubi8/go-toolset:1.19 AS builder
> 
> # Set user as root
> USER root
> 
> # Install yq
> RUN curl -sL -O https://github.com/mikefarah/yq/releases/download/v4.9.5/yq_linux_amd64 -o /usr/local/bin/yq && mv ./yq_linux_amd64 /usr/local/bin/yq && chmod +x /usr/local/bin/yq
> 
> COPY . /registry
> 
> # Download the registry build tools
> RUN git clone --branch feat/index-filtering https://github.com/michael-valdron/devfile-registry-support.git /registry-support
> 
> # Run the registry build tools
> RUN bash /registry-support/build-tools/build.sh /registry /build
> 
> # Set user as non-root
> USER 1001
> 
> FROM quay.io/devfile/devfile-index-base:next
> 
> COPY --from=builder /build /registry
> ```

For everyone's information the issue here was the `quay.io/devfile/devfile-index-base:next`. In order to be able to properly test the changes I had to build the base image from the base branch.

**Comment by Jdubrick** [comment]
Can't seem to build and run the integration tests because my podman alias is not being properly set so I will need to look into this before I can run the tests on my end. I was able to build and deploy the devfile-index however and seemed to work with no issues.

**Comment by michael-valdron** [comment]
> Can't seem to build and run the integration tests because my podman alias is not being properly set so I will need to look into this before I can run the tests on my end. I was able to build and deploy the devfile-index however and seemed to work with no issues.
> 
> Screenshot 2024-04-04 at 4 12 36 PM

Opened https://github.com/devfile/api/issues/1502 to address this along with https://github.com/devfile/api/issues/1503 to discover any other missing/broken `podman` support in our registry-support scripts.

FYI @Jdubrick @thepetk

**Comment by michael-valdron** [comment]
> @michael-valdron as we've checked together (thanks for the help debugging my issue!), I'd suggest adding a custom field for `deprecated` stacks.
> 
> This way when someone needs to fetch a deprecated stack (a stack with the `Deprecated` tag inside the default tags) will fetch only the fully deprecated stacks (without a supported version).
> 
> e.g
> 
> ```
> https://<host>/v2index/all?deprecated=true
> ```

I have included this additional parameter with the some criteria: https://github.com/devfile/api/issues/959#issuecomment-2040398626

FYI @thepetk @Jdubrick

**Pull request merged**
